### ISSUE TITLE
两变量之间的空格被删除了，有什么办法保留吗？

### ISSUE THREAD

**Issue by FisherMS** [jiniannet/jntemplate#10]
$model.AssemblyCopyright      $model.Now.Year

结果成了CSZI.com2017

**Comment by cswares** [comment]
并且我发现前面有空行的变量 结果会把空行都给删除了。

**Comment by FisherMS** [comment]
已经改了源码了。

**Comment by jiniannet** [comment]
默认会清除标签前后的的空白字符，包括空格，换行符等。

解决方法1：如果不需要自动清除，在配置中修改此项设置即可。

`代码如下：
`   var conf = Configuration.EngineConfig.CreateDefault();
            //禁止清除标签前后空白字符
            conf.StripWhiteSpace  = false;
            Engine.Configure(conf);
`

解决方法2：在HTML中使用&amp;nbsp;，比如 ${model.AssemblyCopyright}&amp;nbsp;${model.Now.Year}

**Comment by FisherMS** [comment]
liquid 里有个{- xx -}很好用，左边有-就是删除左边的所有空白，右边有-就是删除右边的所有空白。
我觉得你应该加进去。

我不是生成HTML的，我用来生成代码。
