### ISSUE TITLE
为什么别人的电脑上生成的时候模板引擎有的变量无法替换？

### ISSUE THREAD

**Issue by FisherMS** [jiniannet/jntemplate#11]
我的电脑上没有问题，但是在同事的电脑上的方法调用直接返回模板内容了。如下：

${helper.GetPkQueryParams(table)}

**Comment by jiniannet** [comment]
这是因为执行GetPkQueryParams报错了，

因为你的模板引擎配置了出错后忽略错误继续运行（即不抛出错误），就会出现这种情况

解决方法，设置出错抛出异常 ，然后针对具体的错误原因处理就行。

配置方法：在全局的地方(比如webform中的Global.asax中)配置一下如下代码就行：

`     var conf = Configuration.EngineConfig.CreateDefault();`
 `            //出错时是否抛出异常 `
 `            conf.ThrowExceptions = true;` 
   `          Engine.Configure(conf);
`

默认TRUE的，您那边应该是 配置了 ThrowExceptions = false;,把该行行注释掉，就可以看到具体的错误。

**Comment by FisherMS** [comment]
我这么设置后并没有抛出错误，并且让人疯掉的是，上面的模板变量替换了。下面的新加的却是全部原样输出。使用了 $if(helper.HasOnePrimaryKey(table))    加不加{} 都一样。
这是什么原因？

**Comment by jiniannet** [comment]
请将该页模板发到我的邮箱，有相关代码最好，我帮您看看
邮箱地址见项目主面介绍里面的 联系方式 。发完后在这里回个评论。

**Comment by FisherMS** [comment]
汗，这个BUG不能再现，我把$if 判断挪个位置后，又好了。看来小问题，还是蛮多的。

**Comment by jiniannet** [comment]
这个应该是标签的闭合有问题，建议发出错的模板提 供分析！

**Comment by FisherMS** [comment]
```
$if(helper.HasOnePrimaryKey(table))
		
		/// <summary>
        /// 一次删除多个
        /// </summary>
        /// <param name="ids"></param>
        /// <returns></returns>
	    public virtual int Delete(IEnumerable<$helper.GetOnePkType(table)> ids)
        {
            using (var db = new ${clsDbContext}())
            {
                foreach (var item in ids.Select(id => db.${modelClassName}.Where(x => x.${helper.GetPkName(table)} == id)).SelectMany(items => items))
                {
                    db.${modelClassName}.Remove(item);
                }
                var val = db.SaveChanges();
                return val;
            }
        }
		
		$else

		$end
```

我就是增加了一个空白行，现在好了。不知道删除空白行还会不会出现。

**Comment by jiniannet** [comment]
写法没有问题。尝试多次，无法重现问题！
另外在上面的代码中$else可以省略（不会造成问题）。
