### ISSUE TITLE
1.3.2版本中Template.Render()方法将空格、换行等内容Trim掉了

### ISSUE THREAD

**Issue by dreamofei** [jiniannet/jntemplate#12]
希望模版中的空格、换行符等内容在Render后不变，现在Render后空格都被删掉了

**Comment by jiniannet** [comment]
var conf = Configuration.EngineConfig.CreateDefault();
conf.StripWithSpace =false
Engine.Configure(conf);
在全局的地方配置一下就不会清除空格与换行符了

**Comment by jiniannet** [comment]
webform与asp.net mvc 在 Global.asax中加入上面的代码即可
