### ISSUE TITLE
ITemplate.Set<T>(string key, T value) value为匿名对象时，无法成功赋值

### ISSUE THREAD

**Issue by lingbiaozeng** [jiniannet/jntemplate#23]
NUGET 安装版本：2.3.3
发现匿名对象无发成功赋值：

var templateContent = "hello $model.Name";
var template = Engine.CreateTemplate(templateContent);
template.Set("model",**object匿名对象**);
var result = template.Render(); 
输出 ”hello “

需要进行强制转换才可成功替换标签
template.Set("model",(SiteInfo)**object匿名对象**);

**Comment by jiniannet** [comment]
编译引擎必须为对象指定明确的类型，不能是object，尝试下面的代码，你会明白为什么要这么做

`

 void test1()
{
    SiteInfo model = new SiteInfo()
    {
        Name = "Jntemplate"
    };
    Console.WriteLine(model.Name);//SiteInfo 可以获取到NAME
}

void test2()
{
    object model = new SiteInfo()
    {
        Name = "Jntemplate"
    };
    Console.WriteLine(model.Name);//OBJECT 无法获取到NAME
}

void test3()
{
    var  model = new 
    {
        Name = "Jntemplate"
    };
    Console.WriteLine(model.Name); //真正的匿名类型，可以获取到NAME
}

public class SiteInfo
{
    /// <summary>
    /// 
    /// </summary>
    public string Name { get; set; }
}

`

**Comment by lingbiaozeng** [comment]
感谢您的回复，解惑。

但是请看如下示例：
`static void Main(string[] args)
{
    object model = new SiteInfo()
    {
        Name = "Jntemplate"
    };

    var templateContent = "hello $model.Name";
    var template = Engine.CreateTemplate(templateContent);
    template.Set("model", model);
    var result = template.Render();
    Console.WriteLine(result);
}`
在V2.3.2 以及之前的版本（测试过v2.3.3/v2.2.2），可成功输出“hello Jntemplate”；
但是在v2.3.3 无法获取。“[VariableTag]: "Name" is not defined on model.Name [line:1,col:8]”如你上图的示例，Object是不包含Name属性的。
我想知道的是，为什么V2.3.2可以支持，但是到V2.3.3就不支持了。

**Comment by jiniannet** [comment]
> 感谢您的回复，解惑。
> 
> 但是请看如下示例： `static void Main(string[] args) { object model = new SiteInfo() { Name = "Jntemplate" };
> 
> ```
> var templateContent = "hello $model.Name";
> var template = Engine.CreateTemplate(templateContent);
> template.Set("model", model);
> var result = template.Render();
> Console.WriteLine(result);
> ```
> 
> }` 在V2.3.2 以及之前的版本（测试过v2.3.3/v2.2.2），可成功输出“hello Jntemplate”； 但是在v2.3.3 无法获取。“[VariableTag]: "Name" is not defined on model.Name [line:1,col:8]”如你上图的示例，Object是不包含Name属性的。 我想知道的是，为什么V2.3.2可以支持，但是到V2.3.3就不支持了。

按照设定，为了保证引擎的执行效率，编译引擎必须明确指定类型。
V2.3.2 中，
template.Set("model", model);
在某此情况下，出了点意外，会导致类型没有取model原来的类型(object) 而是取到了（SiteInfo）,导致了在V2.3.2上面的代码可以正常执行

v2.3.3 中，可以理解为修复了此问题，以上代码无法再运行。

如果确实需要如此操作 ，可以考虑使用

> template.Set(string key, object value, Type type) 扩展方法，来替代解决

如：
`
 template.Set("model", model,model.GetType())   //注意model 不能为null
`
