### ISSUE TITLE
JNTemplate比微软官方的好在哪里

### ISSUE THREAD

**Issue by dfengpo** [jiniannet/jntemplate#5]
有什么资料可以证明你的模板引擎比 Razer高吗？
1.易用:上手快，有一定c#基础或者js基础的，只要10分钟就可以学会使用，极大降低学习成本
2.轻量:代码精简，功能不减! 结构清晰，只有最核心的代码， 能适应于绝大部分开发，也能很方便的进行二次开发
3.开源：授权自由，可用于商业目的
4.拓展：引擎可以很方便的过行拓展,甚至可以在不改变原有代码的基础上，很自由的支持解析各种自定义格式的标签

微软最新版的asp.net mvc6 在易用性上要比JNTemplate远远好很多吧，这个不用说了。现在asp.ent vnext 己经把整个framework重写了，各个模块完全独立出来，在实际的开发过程中只需按需引用即可，也变的很轻量级，而且完全开源(https://github.com/aspnet/Mvc)。我真的不知道JNTemplate有什么优势，我找不到一个理由来使用他。

**Comment by jiniannet** [comment]
jntemplate 和 Razor是二种完全不同的引擎，JN是解释型的，RZ是编译型的.

在ASP.NET MVC中，Razor确实是个不错的选择，它与微软自家的东西嵌套的更加紧密，使用更方便是必然的，但是在脱离ASP.NET MVC后，我并不认为Razor易用性更高（参照RazorEngine），而且Razor语法也过于复杂（针对非C#开发人员），

至于速度，因为二者的类型决定，不同的语法/标签，对比结果不同，总体来说，在越频繁的执行过程 中，RZ的速度会越快，比如某些标签，从10W次开始，RZ的速度 就会快起来，而某些标签，则在100W次后也未超过JN, （目前JN的缓存处理方面还没有完善，使用缓存会缩小这种差距），以后缓存完善后可减小这方面差距，另外我也在尝试一些不同的写法，甚至尝试一些使用新的代码来加快处理速度（如果仅用来生成静态页，JN无疑更优秀，因为它单 次执行更快）。

相关方面的资料，别人提 供的都做不得真，自己的测试数据才最管用。建议有兴趣自己测试，我也不在此提 供具体的代码了（包括响应时间 ，内存，CPU占用）。

另外,J因为依赖的引用极少，所以在跨平台方面也很方便，目前从NET 2.0的webform到OWIN,从.NET 到MONO, 都不存问题（当然，在这方面R也现在也不成问题），而且更准确来说。J是一款本文解析引擎，并不仅仅是WEB模板引擎。、

总之，J与R是二个不同类型的引擎，它是你的另外一种选择。
如果你喜欢asp.net MVC,我建议还是使用Razor，如果你喜欢深度定制你的框架，我觉得你可以尝试一下jntemplate(特别是你想基于owin深度定制的情况下)

另外强调 ，Razor是非常优秀的，JNTEMPLATE并不会自称比Razor更好，二者的使用场景，是有所区别的，JNTEMPLATE只是你的另外一个选择

（PS.jntemplate 早期 ，Razor并不如现在普遍，还早点，在jntemplate 的雏形阶段，RAZOR甚至还没有出现，所以RZ一直不是jntemplate参照与对比的对像，上面回复的数据，我也是看到这个Issues，临时做了个做了个简单 对比）。

是吃油条还是包子，是喝豆桨还是咖啡，这只是一个不同的选择。
