### ISSUE TITLE
请问可以解析css文件里的资源路径吗

### ISSUE THREAD

**Issue by dfengpo** [jiniannet/jntemplate#6]
在有些css文件中，比较图片路径，有时候需要使用动态解析的地址，请问如何实现。现在的解决办法是，必需把有路径的样式复制到html文件中才能正常解析。期待你的回复

**Comment by jiniannet** [comment]
这跟在CSS文件或JS文件中写<% %>是一样的情况，
常规情况下是不会解析的，因为静态文件一般是直接输出的，未经过引擎处理。
你要实现你所讲的功能，可以使用httphandler或者类似的机制，使CSS文件在返回给客户端数据前，先经过引擎解析一遍即可。

另外，在CSS的中的图片路径，通常是相对于CSS文件本身的（比如常用的背景片），与页面本身位置关系不大，不需要做动态解析。
